[package]
name = "server_client"
version = "0.1.0"
authors = ["ThePerkinrex <theperkinrex@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "0.4.4"
async-trait = "0.1.41"
tokio = {version = "0.2.22", features=["rt-core"]}
server_client_proc_macro = {path="./server_client_proc_macro"}
